
spring:
  data:
    mongodb:
      uri: mongodb+srv://King:Abcd1234@cluster0.g6sm3im.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal